name: Generate Snake and Pacman Animation

on:
  schedule:
    # Berjalan otomatis setiap 24 jam sekali
    - cron: "0 0 * * *" 
  
  # Mengizinkan Anda menjalankan workflow ini secara manual kapan saja
  workflow_dispatch:
  
  # Berjalan otomatis setiap kali Anda memperbarui README di branch main
  push:
    branches:
    - main
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # --- PROSES CHECKOUT REPOSITORI ---
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- PROSES GENERATE SNAKE ---
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: FaishallRr
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # --- PROSES GENERATE PACMAN ASLI ---
      - name: generate pacman-contribution-graph.svg
        uses: marcinwroblewski/github-contribution-stats@v1.4.0
        with:
          github_user_name: FaishallRr
          # Langkah ini otomatis membuat pacman-contribution-graph.svg & -dark.svg di folder dist

      # --- PUSH SEMUA HASIL KE BRANCH OUTPUT ---
      - name: Push to Output Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: output
          clean: true
